#!/usr/bin/env bash
# This script to transfer a file from our client to a server and requires four parameters.
# We will perform a server content check using the following command:
# ssh ubuntu@35.229.54.225 -i ~/.ssh/holberton 'ls ~/'
# Additionally, we will create a new file named 'newfile.html' using the 'touch' command.
# Post-execution of the script, we will verify if the new content has been successfully transferred to the server by running:
# ssh ubuntu@35.229.54.225 -i ~/.ssh/holberton 'ls ~/'

if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
