#!/usr/bin/env bash
# Starting Apache server
sudo service apache2 start
if sudo service apache2 status | grep -q "apache2 is running"; then
    echo "apache2 is running"
else
    echo "apache2 is not running"
fi
